<a href="https://colab.research.google.com/github/Samyuktha-2/AIML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy - Numerical Python, For fast mathemataical operation.

Numpy - Arrays and Matrix, Used to perform linear algebra
Eg: x + y = 5, 2x + y = 6. Solve the equation. This is linear algebra

Why numpy is faster?
Numpy is implemented by C Program and it uses array to do mathematical operation

In python we store num in list which is slow while making changes because it does everything in loop

Massive numerical datasets are computed using Numpy

Numpy has **ndArray** - which is **N Dimensional Array**.

In [110]:
import numpy as np

In [ ]:
#List in Python
py_list = [1,2,3,4]
print(py_list)
print(type(py_list))

#To multiply all numbers by 2
for i in py_list:
  print(i * 2)

[1, 2, 3, 4]
<class 'list'>
2
4
6
8


In [ ]:
#Array in Numpy
np_array = np.array([1,2,3,4])

print(np_array)
print(type(np_array))
print(np_array.dtype)

np_array = np_array * 2
print(np_array)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
[2 4 6 8]


In [ ]:
scores_list = [1,2,3,4]
scores_array = np.array(scores_list)

print(scores_list)
print(scores_array)
print("")

print("List type: ", type(scores_list))
print("Numpay list type: ", type(scores_array))
print("")

result_list = []
for i in range(0,len(scores_list)):
  result_list.append(scores_list[i] + 10)

print(result_list)

result_array = scores_array + 10
print(result_array)
print("")

print(type(result_list))
print(type(result_array))

[1, 2, 3, 4]
[1 2 3 4]

List type:  <class 'list'>
Numpay list type:  <class 'numpy.ndarray'>

[11, 12, 13, 14]
[11 12 13 14]

<class 'list'>
<class 'numpy.ndarray'>


**DType** - Check what datatype is stored in an array

We can also set datatype manually - int8, int16, int32, int64

int8 stores in 8 Bits
int64 is stores in 64 Bits


There is a datatype called float, starts from float16

In [ ]:
array = np.array([1,2,3,4])
print(array.dtype)
print(array.nbytes)

array1 = np.array([1,2,3,4], dtype = np.int8)
print(array1.dtype)
print(array1.nbytes)

int64
32
int8
4


In [ ]:
array = np.array([12,3,4,5,6], dtype = np.float16)
print(array)
print(array.dtype)
print(array.nbytes)

[12.  3.  4.  5.  6.]
float16
10


**String**

dtype = np.str_

<U3 and <U4 indicates the digit in each value, dtype depends on max digit size on an array

In [ ]:
array = np.array([100,200,300], dtype = np.str_)
print(array)
print(array.dtype)
print(array.nbytes)

['100' '200' '300']
<U3
36


In [ ]:
array = np.array([100,2000,300], dtype = np.str_)
print(array)
print(array.dtype)
print(array.nbytes)

['100' '2000' '300']
<U4
48


In [ ]:
array = np.array(["alex","charlie","Sam"], dtype = np.str_)
print(array)
print(array.dtype)
print(array.nbytes)

['alex' 'charlie' 'Sam']
<U7
84


In [ ]:
array = np.array(["alex","charlie","Sam"], dtype = "<U4")
print(array)
print(array.dtype)
print(array.nbytes)

['alex' 'char' 'Sam']
<U4
48


**Boolean**

dtype = np.bool_

In [ ]:
array = np.array([True,False,False,True], dtype = np.bool_)
print(array)
print(array.dtype)
print(array.nbytes)

[ True False False  True]
bool
4


In [ ]:
array = np.array([1,7,True,"alex","charlie","Sam"])
print(array)
print(array.dtype)
print(array.nbytes)

['1' '7' 'True' 'alex' 'charlie' 'Sam']
<U21
504


In [ ]:
array = np.array([1,7,True,"alex","charlie","Sam"], dtype = np.object_)
print(array)
print(array.dtype)
print(array.nbytes)

[1 7 True 'alex' 'charlie' 'Sam']
object
48


Converting the Datatype

In [ ]:
array = np.array([1,2,3,4,5,6])
print(array)
print(array.dtype)
print(array.nbytes)

array = array.astype(np.str_)
print(array)
print(array.dtype)
print(array.nbytes)

array = array.astype(np.object_)
print(array)
print(array.dtype)
print(array.nbytes)

array = array.astype(np.bool_)
print(array)
print(array.dtype)
print(array.nbytes)


[1 2 3 4 5 6]
int64
48
['1' '2' '3' '4' '5' '6']
<U21
504
['1' '2' '3' '4' '5' '6']
object
48
[ True  True  True  True  True  True]
bool
6


**To check time difference**

In [ ]:
import time as t
import numpy as np

size = 1000000
python_list = list(range(size))
numpy_array = np.arange(size)

start_time = t.time()
result_list = []
for x in python_list:
  result_list.append(x ** 2)
list_duration = t.time() - start_time
print(f"Python list time: {list_duration:.5f} sec")


start_time = t.time()
array_result = numpy_array ** 2
array_duration = t.time() - start_time
print(f"Python list time: {array_duration:.5f} sec")

speedup = list_duration/array_duration
print(speedup)

Python list time: 0.14062 sec
Python list time: 0.00208 sec
67.60671710224668


**Mixed Datatype**

In [ ]:
num = np.array([1,2,3,4])
print(num)
print(num.dtype)

mixed = np.array([1,4.5,"abc"])
print(mixed)
print(mixed.dtype)

[1 2 3 4]
int64
['1' '4.5' 'abc']
<U32


In [ ]:
cel_temp = np.array([0,15,22.5,30,40])
fah_temp = (cel_temp * 9/5) + 32
print(fah_temp)

[ 32.   59.   72.5  86.  104. ]


# **Array Dimension**

**1D Array**

In [ ]:
import numpy as np
arr_1D = np.array([1,2,3,4])
print(type(arr_1D))
print(arr_1D.shape)


<class 'numpy.ndarray'>
(4,)


**2D Array**

In [ ]:
import numpy as np
arr_2d = np.array([[85,92],[90,88],[97,60]])
print(type(arr_2d))
print(arr_2d.shape)

<class 'numpy.ndarray'>
(3, 2)


**3D Array**

In [ ]:
import numpy as np
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d.shape)
print(arr_3d)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Reshape**

In [ ]:
import numpy as np
nums = np.array([[85,92],[90,88],[97,60]])

nums

array([[85, 92],
       [90, 88],
       [97, 60]])

In [ ]:
nums.reshape(2,3)

array([[85],
       [92],
       [90],
       [88],
       [97],
       [60]])

In [ ]:
nums.reshape(1,6)

array([[85, 92, 90, 88, 97, 60]])

In [ ]:
nums.reshape(6,1)

array([[85],
       [92],
       [90],
       [88],
       [97],
       [60]])

In [ ]:
nums.reshape(6,)

array([85, 92, 90, 88, 97, 60])

In [ ]:
np.eye((6))

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
nums=np.array([1,2,3,4,5,6])
nums.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
nums.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
nums.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np
test_scores = np.array([45,82,91,59,73,98,65,29])

passing_marks = test_scores >= 60
print("The fileter mask: ", passing_marks)   #Output array is bool value

passing_scores = test_scores[passing_marks]
print("Filtered scores: ",passing_scores)

The fileter mask:  [False  True  True False  True  True  True False]
Filtered scores:  [82 91 73 98 65]


In [ ]:
import numpy as np
grade_matrix = np.array([
    [80,90,85],
    [95,85,92],
    [60,70,65]
])

subject_means = np.mean(grade_matrix,axis = 0)
print("Subject performance averages: ",subject_means)

student_mean = np.mean(grade_matrix,axis = 1)
print("Student performance average: ",student_mean)


Subject performance averages:  [78.33333333 81.66666667 80.66666667]
Student performance average:  [85.         90.66666667 65.        ]


In [ ]:
import numpy as np
nums = np.array([1,2,3,4,5,6])

print(nums.reshape(-1,2), "\n")
print(nums.reshape(2,-1), "\n")

print(nums.reshape(-1,3))

#print(nums.reshape(-1,4)) raises error

[[1 2]
 [3 4]
 [5 6]] 

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [4 5 6]]


**array.ndim** is used to find dimension

In [ ]:
array = np.array(1)
print(array)
print(array.ndim)

1
0


In [ ]:
array = np.array([1,2,3,4,5])
print(array)
print(array.ndim)

[1 2 3 4 5]
1


In [ ]:
array = np.array([
    [1,2],
    [3,4]
    ])
print(array)
print(array.ndim)

[[1 2]
 [3 4]]
2


Uneven col values are not allowed

In [5]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print(arr.ndim)

print(arr[1][0][1])  #chain indexing
print(arr[1,0,1])    #multi dimensional indexing

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
6
6


**Masai Task**

In [ ]:
import numpy as np

grades = np.array([
    [80, 90, 85],
    [95, 85, 82],
    [60, 70, 65],
    [88, 92, 79]
])

subject_averages = np.mean(grades, axis = 0)

student_averages = np.mean(grades,axis = 1)

high_performers = grades[student_averages >= 80]

reshaped = grades.reshape(2,6)


if __name__ == "__main__":
    print("Subject averages:", subject_averages)
    print("Student averages:", student_averages)
    print("High performers:\n", high_performers)
    print("Reshaped array:\n", reshaped)


Subject averages: [80.75 84.25 77.75]
Student averages: [85.         87.33333333 65.         86.33333333]
High performers:
 [[80 90 85]
 [95 85 82]
 [88 92 79]]
Reshaped array:
 [[80 90 85 95 85 82]
 [60 70 65 88 92 79]]


**array.shape**

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape,"\n")

print(arr.reshape(3,2), "\n")

print(arr.reshape(6,1),"\n")

print(arr.reshape(1,-1),"\n")

(2, 3) 

[[1 2]
 [3 4]
 [5 6]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 

[[1 2 3 4 5 6]] 



# **Slicing**

In [15]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **Row Slicing**

In [16]:
print(arr[0])

[1 2 3]


In [17]:
print(arr[-1])

[7 8 9]


In [18]:
print(arr[-3])

[1 2 3]


In [19]:
print(arr[0][2])

3


In [20]:
print(arr[0,2])

3


In [23]:
print(arr[1:3])  #start(included) : stop(excluded)

[[4 5 6]
 [7 8 9]]


In [26]:
print(arr[0:3:1])  #start : stop : step

[[1 2 3]
 [7 8 9]]


In [28]:
print(arr[0:3:2])

[[1 2 3]
 [7 8 9]]


In [29]:
print(arr[:2])  #start default value 0

[[1 2 3]
 [4 5 6]]


In [30]:
print(arr[1:])  #stop default value n - 1

[[4 5 6]
 [7 8 9]]


In [31]:
print(arr[:-1])

[[1 2 3]
 [4 5 6]]


In [32]:
print(arr[::-1])  #step default value 1

[[7 8 9]
 [4 5 6]
 [1 2 3]]


# **Column Slicing**

In [33]:
print(arr[:,1])

[2 5 8]


In [34]:
print(arr[:,0])

[1 4 7]


In [36]:
print(arr[:,0:2])

[[1 2]
 [4 5]
 [7 8]]


In [37]:
print(arr[:,0::2])

[[1 3]
 [4 6]
 [7 9]]


In [38]:
print(arr[:,::-1])  #col are reversed

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [39]:
print(arr[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [42]:
print(arr[0:2,0:2])

[[1 2]
 [4 5]]


In [43]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

In [44]:
print(matrix[1:3,1:3])

[[ 6  7]
 [10 11]]


# **Arithmetic Operations**

In [45]:
arr = np.array([5,10,15,20])
print(arr)

[ 5 10 15 20]


**Scalar Operation**

In [46]:
print(arr)
print(arr + 5)

[ 5 10 15 20]
[10 15 20 25]


In [47]:
print(arr)
print(arr - 5)

[ 5 10 15 20]
[ 0  5 10 15]


In [48]:
print(arr)
print(arr * 5)

[ 5 10 15 20]
[ 25  50  75 100]


In [49]:
print(arr)
print(arr / 5)

[ 5 10 15 20]
[1. 2. 3. 4.]


In [50]:
print(arr)
print(arr ** 5)

[ 5 10 15 20]
[   3125  100000  759375 3200000]


In [51]:
print(np.sqrt(arr))

[2.23606798 3.16227766 3.87298335 4.47213595]


In [53]:
round_off = np.sqrt(arr)
print(np.round(round_off))
print(np.floor(round_off))  #lower limit
print(np.ceil(round_off))   #Upper limit

[2. 3. 4. 4.]
[2. 3. 3. 4.]
[3. 4. 4. 5.]


In [54]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [57]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [59]:
#To find circumference of circle
print(np.pi)
print(2 * np.pi * arr1)

3.141592653589793
[ 6.28318531 12.56637061 18.84955592]


# **Operators**

In [60]:
age = np.array([43,62,12,34,17,20,30,15,16])
print(age)

[43 62 12 34 17 20 30 15 16]


In [65]:
print("Less than 18: ", age < 18)
print("Greater than 18: ", age > 18)
print("Equal to 18: ", age == 18)
print("Less than equal to 18: ", age <= 18)
print("Greater than equal to 18: ", age >= 18)

Less than 18:  [False False  True False  True False False  True  True]
Greater than 18:  [ True  True False  True False  True  True False False]
Equal to 18:  [False False False False False False False False False]
Less than equal to 18:  [False False  True False  True False False  True  True]
Greater than equal to 18:  [ True  True False  True False  True  True False False]


In [66]:
age[age <= 18] = 0
print(age)

[43 62  0 34  0 20 30  0  0]


# **Broadcasting**
Allows arithmetic operations to be performed between arrays of different shapes by **automatically expanding the smaller array** to match the larger one, without actually copying data in memory

In [72]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr2 = np.array([1,2,3])

"""
1 2 3
1 2 3
1 2 3
"""

'\n1 2 3\n1 2 3\n1 2 3\n'

In [68]:
print(arr1.shape)
print(arr2.shape)

(3, 3)
(3,)


In [69]:
print(arr1 * arr2)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [73]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr2 = np.array([[1],[2],[3]])
"""
1
2
3
"""

'\n1\n2\n3\n'

In [74]:
print(arr1.shape)
print(arr2.shape)

(3, 3)
(3, 1)


In [75]:
print(arr1 * arr2)

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


# **Functions**

In [77]:
#Zero array
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [79]:
arr = np.zeros((10,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [81]:
arr = np.zeros((2,2,2))
print(arr)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [83]:
#One's array
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [85]:
arr = np.ones((5,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [86]:
arr = np.ones((2,2,2))
print(arr)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [88]:
#To create array with same value
arr = np.full(2,3)  #2 column, value needed is 3
print(arr)

[3 3]


In [91]:
arr = np.full((2,3),5)  #2 row,3 column , value needed is 5
print(arr)

[[5 5 5]
 [5 5 5]]


In [93]:
arr = np.full((2,2,3),66)  #2 layer, 2 row,3 column , value needed is 66
print(arr)

[[[66 66 66]
  [66 66 66]]

 [[66 66 66]
  [66 66 66]]]


In [94]:
#Identity matrix
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [97]:
arr = np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


**np.empty()** --> creates a new array of a specified shape and data type without initializing its entries.

Fills array with Garbage values

In [99]:
arr = np.empty(2)
print(arr)

[1. 1.]


In [103]:
arr = np.empty((2,2))
print(arr)

[[2.5e-323 4.9e-323]
 [7.4e-323 9.9e-323]]


In [106]:
arr = np.empty((2,3,3))
print(arr)

[[[1.48770171e-315 0.00000000e+000 5.77969850e-317]
  [6.90708834e-310 6.90708834e-310 6.90708666e-310]
  [6.90708834e-310 5.75761574e-317 6.90708834e-310]]

 [[6.90708834e-310 6.90708834e-310 6.90708769e-310]
  [5.77969850e-317 5.75872640e-317 5.77969850e-317]
  [6.90708769e-310 6.90713410e-310 5.75908213e-317]]]


# **np.arange()**

 Returns an ndarray containing evenly spaced values within a given interval similar like python's Range()

In [108]:
arr = np.arange(4)  #Stop - exclusive, start default = 0
print(arr)

[0 1 2 3]


In [109]:
arr = np.arange(1,4)  #start = 1, stop = 4 - 1
print(arr)

[1 2 3]


In [112]:
arr = np.arange(0,10,2)  #start - 0, stop - 10, step - 2
print(arr)

[0 2 4 6 8]


In [114]:
arr = np.arange(0,10,2.5)
print(arr)

[0.  2.5 5.  7.5]


In [115]:
arr = np.arange(0,40,2).reshape(-1,4)
print(arr)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]]


**np.linspace()**

Creates an array of **evenly spaced numbers** over a specified interval, where you define the start, stop, and the number of points

In [120]:
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


In [121]:
arr = np.linspace(0,1,4)
print(arr)

[0.         0.33333333 0.66666667 1.        ]


In [122]:
arr = np.linspace(0,100,5, endpoint = False) #endpoint false tells to exclude stop value
print(arr)

[ 0. 20. 40. 60. 80.]


In [123]:
arr = np.linspace(0,100,5, endpoint = True) #endpoint true tells to include stop value
print(arr)

[  0.  25.  50.  75. 100.]


# **Aggregate Function**

In [124]:
# argmin, argmax
arr = np.array([[10, 20, 30],
                 [40, 50, 60]])
print(arr)

[[10 20 30]
 [40 50 60]]


In [144]:
print("Sum:", np.sum(arr))
print("Col Sum:", np.sum(arr,axis = 0))
print("Row Sum:", np.sum(arr,axis = 1),"\n")

print("Mean(Avg):", np.mean(arr))
print("Median:", np.median(arr),"\n")

print("Min:", np.min(arr))
print("Col Min:",np.min(arr, axis = 0))
print("Row Min:",np.min(arr, axis = 1),"\n")

print("Max:", np.max(arr))
print("Col Max:",np.max(arr, axis = 0))
print("Row Max:",np.max(arr, axis = 1),"\n")

print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr),"\n")

#arranges array in 1D and returns it's position
print("ArgMin:", np.argmin(arr))
print("ArgMax:", np.argmax(arr))

Sum: 210
Col Sum: [50 70 90]
Row Sum: [ 60 150] 

Mean(Avg): 35.0
Median: 35.0 

Min: 10
Col Min: [10 20 30]
Row Min: [10 40] 

Max: 60
Col Max: [40 50 60]
Row Max: [30 60] 

Standard Deviation: 17.07825127659933
Variance: 291.6666666666667 

ArgMin: 0
ArgMax: 5


# **Filtering**

Filtering in 1D Array

In [153]:
marks = np.array([50,45,84,53,30,75,58])
print(marks)

[50 45 84 53 30 75 58]


In [154]:
pass_mark = marks > 50
print(pass_mark)

pass_mark = marks[marks > 50]
print(pass_mark)

[False False  True  True False  True  True]
[84 53 75 58]


In [155]:
print(marks > 50)
print(marks[marks > 50])

[False False  True  True False  True  True]
[84 53 75 58]


In [158]:
#Take even numbers from marks
even_nums = marks[marks % 2 == 0]
print(even_nums)

[50 84 30 58]


In [159]:
#Print marks above than 50 and below than 70
marks_and = marks[(marks >= 50) & (marks <= 70)]
print(marks_and)

[50 53 58]


In [161]:
#Print marks above than 50 or even mark
marks_or = marks[(marks >= 50) | (marks % 2 == 0)]
print(marks_or)

[50 84 53 30 75 58]


Filtering in Multi-Dimensional Array

Multi dimensional arrays get flatterned and prints the output

In [162]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


In [165]:
even = arr[arr % 2 == 0]
print(even)

even_1 = arr[(arr % 2 == 0) | (arr == 1)]
print(even_1)

[2 4 6]
[1 2 4 6]


To avoid 1D output,we can use WHERE
np.where(condition, arrayVariable, value_to_be_printed_if_value_fails)

In [166]:
even = np.where(arr % 2 == 0, arr, 0)
print(even)

[[0 2 0]
 [4 0 6]]


Can be used in 1D Array also

In [167]:
marks = np.array([50,45,84,53,30,75,58])
even = np.where(marks % 2 == 0, marks, 0)
print(even)

[50  0 84  0 30  0 58]


# **Random Number**

In [190]:
rng = np.random.default_rng()
print(rng.integers(1,31)) #Start (included), stop (excluded)

16


In [172]:
print(rng.integers(low = 1, high = 31))

11


In [173]:
print(rng.integers(low = 1, high = 31, size = (5)))

[29  4 20  3 18]


In [176]:
print(rng.integers(low = 21, high = 31, size = (3,3)))

[[21 21 28]
 [24 25 28]
 [28 24 21]]


In [179]:
print(rng.integers(low = 21, high = 31, size = (2,2,2)))

[[[30 29]
  [28 29]]

 [[30 22]
  [24 28]]]


In [181]:
print(rng.integers(-50,-1,size = 5))

[-45 -45 -31 -12 -11]


In [182]:
print(rng.integers(-50.0,-1.0,size = 5))

[-38 -47 -22 -14  -6]


In [185]:
print(np.random.uniform(1,10,size=4))

[4.29146697 1.21959241 1.89092679 8.02271742]


In [186]:
print(np.random.uniform(1,10,size=(2,2)))

[[4.01977764 9.73310598]
 [1.70689761 9.26901461]]


In [187]:
print(np.random.uniform(1,40,size=(2,2,2)))

[[[10.17693847 21.07226293]
  [ 8.06456579 29.42875983]]

 [[11.08946649 24.62067909]
  [16.43052916 24.89015969]]]


**Shuffle**

In [198]:
arr = np.array(["sam","mithu","vinu","laya"])
rng.shuffle(arr)
print(arr)

['vinu' 'sam' 'laya' 'mithu']


In [211]:
#picks one value from arr randomly
print(rng.choice(arr))

sam


**File Handling**

In [212]:
import os
print(os.getcwd())

/content


In [216]:
arr = np.array([1,2,3,4,5])
np.save("data.npy",arr)

In [217]:
read = np.load("data.npy")
print(read)

[1 2 3 4 5]


In [218]:
#To store multiple arrays we use "savez"
arr2 = np.array([6,7,8,9])
np.savez("data.npz",arr,arr2)


In [220]:
read = np.load("data.npz")
print(read)

NpzFile 'data.npz' with keys: arr_0, arr_1


In [221]:
print(read["arr_0"])
print(read["arr_1"])

[1 2 3 4 5]
[6 7 8 9]


**Linear Algebra**

In [232]:
a =np.array([
    [1,2],
    [3,4]
])

b =np.array([
    [2,2],
    [3,4]
])

print(np.matmul(a,b),"\n")  #row 1 col 1, row 1 col 2, row 2 col 1, row 2 col 2

print(a * b, "\n")

print(np.dot(a,b),"\n")

#Transpose
print(b.T,"\n")

#determinant
print(np.linalg.det(b))

[[ 8 10]
 [18 22]] 

[[ 2  4]
 [ 9 16]] 

[[ 8 10]
 [18 22]] 

[[2 3]
 [2 4]] 

1.9999999999999998
